export enum EVK {
  NODE_ENV = "NODE_ENV",
  PORT = "PORT",
  DB_USERNAME = "DB_USERNAME",
  DB_PASSSWORD = "DB_PASSSWORD",
  DB_NAME = "DB_NAME",
  REDIS_PORT = "REDIS_PORT",
  REDIS_HOST = "REDIS_HOST",
  RELEASE_VERSION = "RELEASE_VERSION",
  PHOT_AI_API_KEY = "PHOT_AI_API_KEY",
  PHOT_AI_API_URL = "PHOT_AI_API_URL"
}
